#!/bin/sh

IMAGE="elixir:1.8.1-alpine"
PWD=$(pwd)
DCNAME=$(basename "${PWD}")

if [ -z "${PORT}" ]; then
	PORTSTR=""
else
	echo "--- using port: ${PORT}"
	PORTSTR="-p ${PORT}:${PORT}"
fi

if [ -z "${NETWORK}" ]; then
	NETSTR=""
else
	NETSTR="--network=${DCNAME}_${NETWORK}"
fi

ENVFILE="./.env"

touch "${ENVFILE}"

if [ -z "${NAME}" ]; then
	# no name specified, so leave blank so docker will make a random name
	NAMESTR=""
else
	NAME="${DCNAME}_${NAME}"
	NAMESTR="--name ${NAME}"
fi

docker run \
	-it \
	--rm=true \
	${NAMESTR} \
	--env-file "${ENVFILE}" \
	${PORTSTR} \
	${NETSTR} \
	-v "${PWD}:/app" \
	-v "${PWD}/elixir-mix:/root/.mix" \
	-w /app \
	"${IMAGE}" $@
